FROM registry.fedoraproject.org/fedora:latest@sha256:ba35579e107f26a4c2c000390fb3ff549f3858a9584a6b5a35f7fa51f54de309 AS build-env

RUN mkdir /output
RUN dnf -y --installroot=/output --use-host-config --setopt=install_weak_deps=false --nodocs install \
    glibc-minimal-langpack coreutils-single bash bind-utils ca-certificates curl dnf findutils \
    gawk grep iproute iputils jq less mtr openssh-clients openssl \
    postgresql procps-ng sed socat tcpdump tcptraceroute traceroute util-linux \
    vim-minimal && \
    dnf -y --installroot=/output clean all

RUN mkdir -p /output/root && printf '%s\n' \
    "alias cp='cp -i'" \
    "alias egrep='grep -E --color=auto'" \
    "alias fgrep='grep -F --color=auto'" \
    "alias grep='grep --color=auto'" \
    "alias l.='ls -d .* --color=auto'" \
    "alias ll='ls -l --color=auto'" \
    "alias ls='ls --color=auto'" \
    "alias mv='mv -i'" \
    "alias rm='rm -i'" \
    > /output/root/.bashrc

FROM scratch
LABEL org.opencontainers.image.authors="Bengt <bengt@fredhs.net>"
COPY --from=build-env /output /

WORKDIR /root

ENTRYPOINT ["tail", "-f", "/dev/null"]
